services:
  dash_app:
    build: .
    container_name: dash_app
    ports:
      - "8000:8000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - "C:/Covenant/code_maker/nginx/default.conf:/etc/nginx/conf.d/default.conf"  # 올바른 절대 경로 사용
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - dash_app
